[book]
authors = ["Henk Dieter Oordt"]
language = "en"
multilingual = false
src = "lectures/mdbook/src"
title = "TG Rust embedded workshop"


[output.html]
additional-css = ["lectures/mdbook/src/assets/style/main.css"]
